package com.xunlei.download.utils.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "AD".
 */
public class ADDao extends AbstractDao<AD, Integer> {

    public static final String TABLENAME = "AD";

    /**
     * Properties of entity AD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Integer.class, "ID", true, "ID");
        public final static Property URL = new Property(1, String.class, "URL", false, "URL");
        public final static Property APKNAME = new Property(2, String.class, "APKNAME", false, "APKNAME");
    }

    ;


    public ADDao(DaoConfig config) {
        super(config);
    }

    public ADDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"AD\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: ID
                "\"URL\" TEXT," + // 1: URL
                "\"APKNAME\" TEXT);"); // 2: APKNAME
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AD\"";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, AD entity) {
        stmt.clearBindings();

        Integer ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }

        String URL = entity.getURL();
        if (URL != null) {
            stmt.bindString(2, URL);
        }

        String APKNAME = entity.getAPKNAME();
        if (APKNAME != null) {
            stmt.bindString(3, APKNAME);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public AD readEntity(Cursor cursor, int offset) {
        AD entity = new AD( //
                cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // ID
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // URL
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // APKNAME
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, AD entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setURL(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAPKNAME(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Integer updateKeyAfterInsert(AD entity, long rowId) {
        return entity.getID();
    }

    /**
     * @inheritdoc
     */
    @Override
    public Integer getKey(AD entity) {
        if (entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
